---
- name: copy sound warning video
  become: yes
  copy:
    src: "{{ akku_warning.multimedia.sound_src }}"
    dest: "{{ akku_warning.multimedia.sound_dest }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: multimedia_akku_warning | bool
