---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: copy sound warning script
  become: yes
  template:
    src: 'templates/akku.sh'
    dest: '/opt/akku.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: copy sound warning video
  become: yes
  copy:
    src: "{{ akku_sound_src }}"
    dest: "{{ akku_sound_dest }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: multimedia_akku_warning|bool

- name: install zenity and mpv for notifications
  become: yes
  package:
    name:
      - zenity
      - mpv
    state: present

- name: Check akku every 2 minutes
  become: yes
  cron:
    name: check if akku still okay
    job: /opt/akku.sh
    minute: '*/3'
    user: '{{ akku_user }}'
    cron_file: /etc/crontab

- name: Make sure cron is installed
  become: true
  when: install_and_enable_cronie|bool
  package:
    name:
      - cronie
    state: present

- name: Make sure cron is running
  become: true
  when: install_and_enable_cronie|bool
  systemd:
    name: cronie.service
    state: started
    enabled: yes
    daemon_reload: yes
