---
- name: combine akku_warning config
  set_fact:
    akku_warning: "{{ _akku_warning|combine(akku_warning, recursive=True) }}"

- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: copy sound warning script
  become: yes
  template:
    src: 'templates/akku.sh'
    dest: "{{ akku_warning.script_dest }}"
    owner: 'root'
    group: 'root'
    mode: '0755'

- include_tasks: copy_media_files.yml
  when: akku_warning.multimedia_support | bool

- include_tasks: install_packages.yml
  when: akku_warning.manage_packages | bool

- name: Check akku every 2 minutes
  become: yes
  cron:
    name: check if akku still okay
    job: /opt/akku.sh
    minute: '*/3'
    user: '{{ akku_warning.user }}'
    cron_file: /etc/crontab
